### ISSUE TITLE
Decimal Point not always displaying

### ISSUE THREAD

**Issue by secretplop** [fatboychummy/Simplify-Shop#4]
**Describe the bug**
Decimal point on prices not always displayed.
eg 25.00 showing as 2500

**To Reproduce**
1. Set an items price to 25
2. Start shop

**Expected behavior**
It should display 25.00 instead of 2500

**Screenshots**
https://i.imgur.com/xxG5vBB.png
Ignore the text that escaped the box

**Additional context**
no

**Comment by fatboychummy** [comment]
hmm seems like an error with the way it sets the cursor position, I'm assuming a rounding error somewhere in there, will figure it out tonight.

**Comment by fatboychummy** [comment]
![image](https://user-images.githubusercontent.com/39929480/41075737-4b1146c0-69cb-11e8-8603-feaae183dd73.png)
![image](https://user-images.githubusercontent.com/39929480/41075745-53743994-69cb-11e8-916a-899495da08b9.png)
Yep, definitely a rounding error in setCursorPos()
Works on larger width monitors, but if you shorten the width a bit it does it.

**Comment by fatboychummy** [comment]
This should be fixed now with Hotfix 1.01.
